[project]
name = "python-embedder"
version = "0.1.0"
description = "Precomputes embeddings for sqlite database"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sentence-transformers>=5.2.3",
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
]
